name:                handwritten-dfa
version:             0.1.0.0
github:              hjkcai/PLP4e
license:             MIT
author:              hjkcai
maintainer:          huajingkun1214@gmail.com
copyright:           2019 Jingkun Hua

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  handwritten-dfa-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handwritten-dfa
